server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://dpg-cpitgmi1hbls73bmt4vg-a/dbong
    username: admin
    password: 4dHgVgkkzj5tO9NjocMFPHT569OQ0dO9
    driver-class-name: org.postgresql.Driver
    initialize: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true

  sql:
    init:
      schema-locations: classpath:/schema-postgresql.sql
      mode: always
      platform: postgres
